"""
Elasticsearch MCP Server

Exposes Elasticsearch semantic search capabilities as MCP tools.
No external LLMs are used – all embeddings are generated by models
deployed directly inside Elasticsearch (ELSER, E5, etc.).
"""

from __future__ import annotations

import json
import logging
from typing import Any, Optional

import mcp.types as types
from mcp.server import Server
from mcp.server.models import InitializationOptions

from .config import ElasticsearchConfig
from .es_client import ElasticsearchClient
from .index_setup import (
    dense_index_mapping,
    dense_ingest_pipeline,
    elser_index_mapping,
    elser_ingest_pipeline,
    get_model_dims,
    hybrid_index_mapping,
    semantic_text_index_mapping,
)
from .query_builder import (
    build_elser_query,
    build_hybrid_query,
    build_knn_query,
    build_rrf_query,
    build_semantic_text_query,
    parse_hits,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Server factory
# ---------------------------------------------------------------------------


def create_server(config: Optional[ElasticsearchConfig] = None) -> Server:
    """Create and configure the MCP server instance."""
    if config is None:
        config = ElasticsearchConfig.from_env()

    es = ElasticsearchClient(config)
    server = Server("elasticsearch-semantic-search")

    # -----------------------------------------------------------------------
    # Tool: list_tools (handled by MCP SDK automatically via decorator)
    # -----------------------------------------------------------------------

    @server.list_tools()
    async def list_tools() -> list[types.Tool]:
        return _build_tool_list()

    # -----------------------------------------------------------------------
    # Tool dispatcher
    # -----------------------------------------------------------------------

    @server.call_tool()
    async def call_tool(
        name: str, arguments: dict[str, Any]
    ) -> list[types.TextContent]:
        try:
            result = await _dispatch(name, arguments, es, config)
            return [types.TextContent(type="text", text=json.dumps(result, indent=2))]
        except Exception as exc:
            logger.exception("Tool '%s' failed", name)
            error_payload = {"error": str(exc), "tool": name}
            return [
                types.TextContent(type="text", text=json.dumps(error_payload, indent=2))
            ]

    return server


# ---------------------------------------------------------------------------
# Tool definitions
# ---------------------------------------------------------------------------


def _build_tool_list() -> list[types.Tool]:
    return [
        # -- Cluster / index info -------------------------------------------
        types.Tool(
            name="es_ping",
            description="Ping the Elasticsearch cluster and return basic info.",
            inputSchema={"type": "object", "properties": {}, "required": []},
        ),
        types.Tool(
            name="es_list_indices",
            description="List all indices in the cluster, optionally filtered by pattern.",
            inputSchema={
                "type": "object",
                "properties": {
                    "pattern": {
                        "type": "string",
                        "description": "Index name pattern (e.g. 'logs-*'). Defaults to '*'.",
                        "default": "*",
                    }
                },
                "required": [],
            },
        ),
        types.Tool(
            name="es_get_mapping",
            description="Return the field mappings for an index.",
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string", "description": "Index name."}
                },
                "required": ["index"],
            },
        ),
        types.Tool(
            name="es_list_ml_models",
            description="List ML models deployed in Elasticsearch (ELSER, E5, etc.).",
            inputSchema={"type": "object", "properties": {}, "required": []},
        ),
        types.Tool(
            name="es_model_stats",
            description="Get deployment statistics for a specific ML model.",
            inputSchema={
                "type": "object",
                "properties": {
                    "model_id": {
                        "type": "string",
                        "description": "Model ID (e.g. '.elser_model_2').",
                    }
                },
                "required": ["model_id"],
            },
        ),
        # -- Semantic search ------------------------------------------------
        types.Tool(
            name="es_semantic_search_elser",
            description=(
                "Sparse semantic search using ELSER (Elastic Learned Sparse EncodeR). "
                "Best for English text. The field must be mapped as sparse_vector and "
                "populated via an ELSER ingest pipeline."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string", "description": "Index to search."},
                    "query": {"type": "string", "description": "Natural language query."},
                    "field": {
                        "type": "string",
                        "description": "sparse_vector field name.",
                    },
                    "model_id": {
                        "type": "string",
                        "description": "ELSER model ID.",
                        "default": ".elser_model_2",
                    },
                    "size": {
                        "type": "integer",
                        "description": "Number of results to return.",
                        "default": 10,
                    },
                    "min_score": {
                        "type": "number",
                        "description": "Minimum relevance score threshold.",
                        "default": 0.0,
                    },
                    "filter": {
                        "type": "object",
                        "description": "Optional Elasticsearch filter query.",
                    },
                    "source_fields": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Fields to include in results (_source filter).",
                    },
                    "highlight_field": {
                        "type": "string",
                        "description": "Field to highlight matching passages in.",
                    },
                },
                "required": ["index", "query", "field"],
            },
        ),
        types.Tool(
            name="es_semantic_search_knn",
            description=(
                "Dense-vector kNN semantic search using Elasticsearch text-embedding "
                "models (e.g. multilingual-e5-small). The field must be a dense_vector "
                "field with index=true. Embeddings are generated inside Elasticsearch."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string", "description": "Index to search."},
                    "query": {"type": "string", "description": "Natural language query."},
                    "field": {
                        "type": "string",
                        "description": "dense_vector field name.",
                    },
                    "model_id": {
                        "type": "string",
                        "description": "Text embedding model ID.",
                        "default": ".multilingual-e5-small",
                    },
                    "k": {
                        "type": "integer",
                        "description": "Number of nearest neighbours to return.",
                        "default": 10,
                    },
                    "num_candidates": {
                        "type": "integer",
                        "description": "ANN candidate pool size (>= k).",
                        "default": 100,
                    },
                    "filter": {
                        "type": "object",
                        "description": "Optional Elasticsearch filter query.",
                    },
                    "source_fields": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Fields to include in results.",
                    },
                },
                "required": ["index", "query", "field"],
            },
        ),
        types.Tool(
            name="es_semantic_search_hybrid",
            description=(
                "Hybrid search: ELSER sparse semantic + BM25 keyword, combined with "
                "configurable boosts. Good for balancing precision with recall."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string", "description": "Index to search."},
                    "query": {"type": "string", "description": "Natural language query."},
                    "semantic_field": {
                        "type": "string",
                        "description": "sparse_vector field for ELSER.",
                    },
                    "keyword_fields": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Text fields for BM25 keyword matching.",
                    },
                    "model_id": {
                        "type": "string",
                        "description": "ELSER model ID.",
                        "default": ".elser_model_2",
                    },
                    "semantic_boost": {
                        "type": "number",
                        "description": "Boost multiplier for semantic score.",
                        "default": 1.0,
                    },
                    "keyword_boost": {
                        "type": "number",
                        "description": "Boost multiplier for keyword score.",
                        "default": 0.5,
                    },
                    "size": {"type": "integer", "default": 10},
                    "min_score": {"type": "number", "default": 0.0},
                    "filter": {"type": "object"},
                    "source_fields": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["index", "query", "semantic_field", "keyword_fields"],
            },
        ),
        types.Tool(
            name="es_semantic_search_rrf",
            description=(
                "Hybrid search with Reciprocal Rank Fusion (RRF) – requires ES 8.8+. "
                "Merges dense kNN and BM25 rankings without manual score tuning."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "query": {"type": "string"},
                    "dense_field": {
                        "type": "string",
                        "description": "dense_vector field for kNN.",
                    },
                    "keyword_fields": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Text fields for BM25.",
                    },
                    "model_id": {
                        "type": "string",
                        "default": ".multilingual-e5-small",
                    },
                    "k": {"type": "integer", "default": 10},
                    "num_candidates": {"type": "integer", "default": 100},
                    "rrf_rank_constant": {"type": "integer", "default": 60},
                    "rrf_window_size": {"type": "integer", "default": 100},
                    "size": {"type": "integer", "default": 10},
                    "filter": {"type": "object"},
                    "source_fields": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["index", "query", "dense_field", "keyword_fields"],
            },
        ),
        types.Tool(
            name="es_semantic_search_native",
            description=(
                "Query a `semantic_text` field (ES 8.11+). The simplest approach – "
                "model and storage are fully managed by Elasticsearch at the field level."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "query": {"type": "string"},
                    "field": {
                        "type": "string",
                        "description": "semantic_text field name.",
                    },
                    "size": {"type": "integer", "default": 10},
                    "min_score": {"type": "number", "default": 0.0},
                    "filter": {"type": "object"},
                    "source_fields": {"type": "array", "items": {"type": "string"}},
                    "highlight_field": {"type": "string"},
                },
                "required": ["index", "query", "field"],
            },
        ),
        # -- Index / pipeline setup -----------------------------------------
        types.Tool(
            name="es_setup_elser_index",
            description=(
                "Create an index + ingest pipeline configured for ELSER sparse "
                "semantic search. Run this once before indexing documents."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string", "description": "Index name to create."},
                    "text_field": {
                        "type": "string",
                        "description": "Raw text field name.",
                        "default": "content",
                    },
                    "sparse_field": {
                        "type": "string",
                        "description": "sparse_vector field name.",
                        "default": "content_embedding",
                    },
                    "model_id": {
                        "type": "string",
                        "default": ".elser_model_2",
                    },
                    "pipeline_id": {
                        "type": "string",
                        "description": "Ingest pipeline ID to create.",
                        "default": "elser-embedding-pipeline",
                    },
                    "extra_fields": {
                        "type": "object",
                        "description": "Additional field mappings to include.",
                    },
                },
                "required": ["index"],
            },
        ),
        types.Tool(
            name="es_setup_dense_index",
            description=(
                "Create an index + ingest pipeline for dense-vector kNN semantic "
                "search using a text-embedding model (e.g. multilingual-e5-small)."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "text_field": {"type": "string", "default": "content"},
                    "vector_field": {
                        "type": "string",
                        "default": "content_vector",
                    },
                    "model_id": {
                        "type": "string",
                        "default": ".multilingual-e5-small",
                    },
                    "dims": {
                        "type": "integer",
                        "description": "Vector dimensions (auto-detected for known models).",
                    },
                    "similarity": {
                        "type": "string",
                        "enum": ["cosine", "dot_product", "l2_norm"],
                        "default": "cosine",
                    },
                    "pipeline_id": {
                        "type": "string",
                        "default": "dense-embedding-pipeline",
                    },
                    "extra_fields": {"type": "object"},
                },
                "required": ["index"],
            },
        ),
        types.Tool(
            name="es_create_ingest_pipeline",
            description="Create or update a custom Elasticsearch ingest pipeline.",
            inputSchema={
                "type": "object",
                "properties": {
                    "pipeline_id": {"type": "string"},
                    "pipeline_body": {
                        "type": "object",
                        "description": "Full pipeline definition (description + processors).",
                    },
                },
                "required": ["pipeline_id", "pipeline_body"],
            },
        ),
        types.Tool(
            name="es_get_ingest_pipeline",
            description="Retrieve an existing ingest pipeline definition.",
            inputSchema={
                "type": "object",
                "properties": {"pipeline_id": {"type": "string"}},
                "required": ["pipeline_id"],
            },
        ),
        # -- Document management --------------------------------------------
        types.Tool(
            name="es_index_document",
            description=(
                "Index a single document. Pass `pipeline` to run it through "
                "an embedding ingest pipeline automatically."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "document": {
                        "type": "object",
                        "description": "Document fields as a JSON object.",
                    },
                    "doc_id": {
                        "type": "string",
                        "description": "Optional document ID.",
                    },
                    "pipeline": {
                        "type": "string",
                        "description": "Ingest pipeline to run during indexing.",
                    },
                },
                "required": ["index", "document"],
            },
        ),
        types.Tool(
            name="es_bulk_index",
            description=(
                "Bulk-index multiple documents. Pass `pipeline` to generate "
                "embeddings automatically during ingestion."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "documents": {
                        "type": "array",
                        "items": {"type": "object"},
                        "description": "List of document objects to index.",
                    },
                    "pipeline": {"type": "string"},
                },
                "required": ["index", "documents"],
            },
        ),
        # -- Raw search -----------------------------------------------------
        types.Tool(
            name="es_raw_search",
            description=(
                "Execute an arbitrary Elasticsearch search query body. "
                "Use for advanced queries not covered by other tools."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "body": {
                        "type": "object",
                        "description": "Raw Elasticsearch query DSL body.",
                    },
                    "size": {"type": "integer", "default": 10},
                },
                "required": ["index", "body"],
            },
        ),
        types.Tool(
            name="es_delete_index",
            description="Delete an Elasticsearch index.",
            inputSchema={
                "type": "object",
                "properties": {
                    "index": {"type": "string"},
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to proceed.",
                    },
                },
                "required": ["index", "confirm"],
            },
        ),
    ]


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------


async def _dispatch(
    name: str,
    args: dict[str, Any],
    es: ElasticsearchClient,
    config: ElasticsearchConfig,
) -> Any:
    # -- Cluster / index info -----------------------------------------------
    if name == "es_ping":
        alive = await es.ping()
        if alive:
            info = await es.cluster_info()
            return {
                "status": "connected",
                "cluster_name": info.get("cluster_name"),
                "version": info.get("version", {}).get("number"),
            }
        return {"status": "unreachable"}

    if name == "es_list_indices":
        return await es.list_indices(args.get("pattern", "*"))

    if name == "es_get_mapping":
        return await es.get_mapping(args["index"])

    if name == "es_list_ml_models":
        return await es.get_ml_models()

    if name == "es_model_stats":
        return await es.model_deployment_stats(args["model_id"])

    # -- Semantic search ----------------------------------------------------
    if name == "es_semantic_search_elser":
        body = build_elser_query(
            query_text=args["query"],
            field=args["field"],
            model_id=args.get("model_id", config.default_model_id),
            filter_=args.get("filter"),
            source_fields=args.get("source_fields"),
            highlight_field=args.get("highlight_field"),
        )
        size = args.get("size", config.default_top_k)
        resp = await es.execute_search(args["index"], body, size=size)
        hits = parse_hits(resp, min_score=args.get("min_score", config.default_min_score))
        return {
            "total": resp.get("hits", {}).get("total", {}).get("value", 0),
            "hits": hits,
        }

    if name == "es_semantic_search_knn":
        body = build_knn_query(
            query_text=args["query"],
            field=args["field"],
            model_id=args.get("model_id", config.default_dense_model_id),
            k=args.get("k", config.default_top_k),
            num_candidates=args.get("num_candidates", config.default_num_candidates),
            filter_=args.get("filter"),
            source_fields=args.get("source_fields"),
        )
        resp = await es.execute_search(args["index"], body, size=args.get("k", config.default_top_k))
        hits = parse_hits(resp, min_score=0.0)
        return {
            "total": resp.get("hits", {}).get("total", {}).get("value", 0),
            "hits": hits,
        }

    if name == "es_semantic_search_hybrid":
        body = build_hybrid_query(
            query_text=args["query"],
            semantic_field=args["semantic_field"],
            keyword_fields=args["keyword_fields"],
            model_id=args.get("model_id", config.default_model_id),
            semantic_boost=args.get("semantic_boost", 1.0),
            keyword_boost=args.get("keyword_boost", 0.5),
            filter_=args.get("filter"),
            source_fields=args.get("source_fields"),
            highlight_field=args.get("highlight_field"),
        )
        size = args.get("size", config.default_top_k)
        resp = await es.execute_search(args["index"], body, size=size)
        hits = parse_hits(resp, min_score=args.get("min_score", config.default_min_score))
        return {
            "total": resp.get("hits", {}).get("total", {}).get("value", 0),
            "hits": hits,
        }

    if name == "es_semantic_search_rrf":
        body = build_rrf_query(
            query_text=args["query"],
            dense_field=args["dense_field"],
            keyword_fields=args["keyword_fields"],
            model_id=args.get("model_id", config.default_dense_model_id),
            k=args.get("k", config.default_top_k),
            num_candidates=args.get("num_candidates", config.default_num_candidates),
            rrf_rank_constant=args.get("rrf_rank_constant", 60),
            rrf_window_size=args.get("rrf_window_size", 100),
            filter_=args.get("filter"),
            source_fields=args.get("source_fields"),
        )
        size = args.get("size", config.default_top_k)
        resp = await es.execute_search(args["index"], body, size=size)
        hits = parse_hits(resp, min_score=0.0)
        return {
            "total": resp.get("hits", {}).get("total", {}).get("value", 0),
            "hits": hits,
        }

    if name == "es_semantic_search_native":
        body = build_semantic_text_query(
            query_text=args["query"],
            field=args["field"],
            filter_=args.get("filter"),
            source_fields=args.get("source_fields"),
            highlight_field=args.get("highlight_field"),
        )
        size = args.get("size", config.default_top_k)
        resp = await es.execute_search(args["index"], body, size=size)
        hits = parse_hits(resp, min_score=args.get("min_score", config.default_min_score))
        return {
            "total": resp.get("hits", {}).get("total", {}).get("value", 0),
            "hits": hits,
        }

    # -- Index / pipeline setup --------------------------------------------
    if name == "es_setup_elser_index":
        index = args["index"]
        text_field = args.get("text_field", "content")
        sparse_field = args.get("sparse_field", "content_embedding")
        model_id = args.get("model_id", config.default_model_id)
        pipeline_id = args.get("pipeline_id", "elser-embedding-pipeline")
        extra_fields = args.get("extra_fields")

        # Create pipeline
        pid, pbody = elser_ingest_pipeline(pipeline_id, text_field, sparse_field, model_id)
        pipeline_resp = await es.create_ingest_pipeline(pid, pbody)

        # Create index
        mapping = elser_index_mapping(text_field, sparse_field, extra_fields)
        index_resp = await es.create_index(index, mapping)

        return {
            "index": index_resp,
            "pipeline": pipeline_resp,
            "next_steps": (
                f"Index documents with pipeline='{pipeline_id}'. "
                f"Then search with es_semantic_search_elser using field='{sparse_field}'."
            ),
        }

    if name == "es_setup_dense_index":
        index = args["index"]
        text_field = args.get("text_field", "content")
        vector_field = args.get("vector_field", "content_vector")
        model_id = args.get("model_id", config.default_dense_model_id)
        pipeline_id = args.get("pipeline_id", "dense-embedding-pipeline")
        extra_fields = args.get("extra_fields")
        similarity = args.get("similarity", "cosine")

        dims = args.get("dims") or get_model_dims(model_id)
        if not dims:
            raise ValueError(
                f"Cannot auto-detect dims for model '{model_id}'. "
                "Please provide 'dims' explicitly."
            )

        pid, pbody = dense_ingest_pipeline(pipeline_id, text_field, vector_field, model_id)
        pipeline_resp = await es.create_ingest_pipeline(pid, pbody)

        mapping = dense_index_mapping(text_field, vector_field, dims, similarity, extra_fields)
        index_resp = await es.create_index(index, mapping)

        return {
            "index": index_resp,
            "pipeline": pipeline_resp,
            "dims": dims,
            "next_steps": (
                f"Index documents with pipeline='{pipeline_id}'. "
                f"Then search with es_semantic_search_knn using field='{vector_field}'."
            ),
        }

    if name == "es_create_ingest_pipeline":
        return await es.create_ingest_pipeline(args["pipeline_id"], args["pipeline_body"])

    if name == "es_get_ingest_pipeline":
        return await es.get_ingest_pipeline(args["pipeline_id"])

    # -- Document management -----------------------------------------------
    if name == "es_index_document":
        return await es.index_document(
            index=args["index"],
            document=args["document"],
            doc_id=args.get("doc_id"),
            pipeline=args.get("pipeline"),
        )

    if name == "es_bulk_index":
        return await es.bulk_index(
            index=args["index"],
            documents=args["documents"],
            pipeline=args.get("pipeline"),
        )

    if name == "es_raw_search":
        resp = await es.execute_search(args["index"], args["body"], size=args.get("size", 10))
        return resp

    if name == "es_delete_index":
        if not args.get("confirm", False):
            return {"error": "Set 'confirm': true to delete the index."}
        return await es.delete_index(args["index"])

    raise ValueError(f"Unknown tool: {name}")
